clear ;close all;
[xn,Fs]=audioread('SunshineSquare.wav');
Y=fft(xn);len=length(xn);t=(0:len-1)/Fs;w=(0:len-1)*2*pi/len;
%滤波操作
f=0.99;
a=[1,f,f^2];
b1=[1,-2*cos(0),1];
b2=[1,-2*cos(0.2857*pi),1];
b3=[1,-2*cos(0.5714*pi),1];
b4=[1,-2*cos(0.8571*pi),1];
audio=filter(b1,b1.*a,xn);
audio=filter(b2,b2.*a,audio);
audio=filter(b3,b3.*a,audio);
audio=filter(b4,b4.*a,audio);
%进行第二次滤波
audio=filter(b1,b1.*a,audio);
audio=filter(b2,b2.*a,audio);
audio=filter(b3,b3.*a,audio);
audio=filter(b4,b4.*a,audio);
%做出滤波器图像函数
[H1,W1]=freqz(b1,b1.*a,w);
[H2,W2]=freqz(b2,b2.*a,w);
[H3,W3]=freqz(b3,b3.*a,w);
[H4,W4]=freqz(b4,b4.*a,w);
H=H1.*H2.*H3.*H4;

figure(1);
subplot(2,1,1);plot(t,xn);title("Time");
subplot(2,1,2);plot(t,audio);title("Time_new");
figure(2);
subplot(2,1,1);plot(w/pi,abs(Y));title("frequency");
subplot(2,1,2);plot(w/pi,abs(fft(audio)));title("frequency_new");
figure(3);
plot(w/pi,abs(H));title("fliter");
soundsc(audio,Fs);